custom:
  awsProfile: ${file(env.yml):awsProfile}

service: cloudfront-s3-index-extension-remover

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  memorySize: 128
  timeout: 30 # maximum 30 seconds for viewer-request events
  profile: ${self:custom.awsProfile} # aws named profile
  stage: ${opt:stage, 'dev'} # `sls deploy --stage production` if --stage is provided, else use dev

functions:
  removeExtension:
    handler: handler.removeExtension
